FROM node:22-alpine AS builder

WORKDIR /app/src

COPY . .

RUN npm i && npm run build

FROM node:22-alpine AS prod

WORKDIR /app/src

COPY --from=builder /app/src/package* ./
COPY --from=builder /app/src/node_modules/ ./node_modules/
COPY --from=builder /app/src/dist/ ./dist/
COPY --from=builder /app/src/client ./client

CMD ["node", "dist/index.js"]
